---
title: "creating_move2_obj"
output: html_document
---


```{r echo=FALSE, results='hide'}
library(dplyr)
# remove colony information from the dataset
boobies <- track2KBA::boobies %>%
  select(-c(lon_colony, lat_colony)) %>%
  mutate(track_id = as.factor(track_id))

```

Let's inspect the table
```{r}
summary(boobies)
```

We start by combining the `data_gmt` and `time_gmt` columns into a single `POSIXct`,
using the `lubridate` package, and then removing the original columns. 
```{r}
library(dplyr)
library(lubridate)
boobies <- boobies %>%
  mutate(date_time = ymd_hms(paste(date_gmt, time_gmt))) %>%
  select(-c(date_gmt, time_gmt))
head(boobies)
```

Next, we convert the data into an `sf` object.
```{r}
library(sf)
boobies_sf <- st_as_sf(boobies, coords = c("longitude", "latitude"),
                       crs = "+proj=longlat +datum=WGS84")
summary(boobies_sf)
```

We are now ready to cast the data into a `move2` object, which we will then
use as the base of our analysis:
```{r}
library(move2)
boobies_move <- mt_as_move2(boobies_sf, track_id_column = "track_id",
                            time_column = "date_time")
```
